### ISSUE TITLE
[book] Re-coding America

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/book-club#2]
## The book

[Re-coding America](https://us.macmillan.com/books/9781250266774/recodingamerica), Why Government Is Failing in the Digital Age and How We Can Do Better, by Jennifer Pahlka

Suggested by @jules32 @stefaniebutland @monicagerber

**Why read it? What is the book's relevance to the Openscapes community?** 

Author Jennifer Pahlka is President Obama's former deputy chief technology officer and the founder of Code for America. Super engaging book. Examples come from US gov organizations and will be so relatable to NASA, NOAA, folks who have participated in Openscapes programs. Compelling human stories that illustrate the value of truly agile development, in contrast to waterfall style embedded in US gov processes.

**Comment by stefaniebutland** [comment]
@monicagerber any thoughts off the top of your head about is book? In the new year we'd love to Zoom about it with you and others who might want to join.

**Comment by jules32** [comment]
This is a book about change-makers and empowering teams and I love it. I've been recommending it to many people, and here's what I keep finding myself sharing as a summary: 

Of the many eye-opening topics of the book, the Waterfall concept floored me. I am familiar with Agile, but hadn't considered the alternative, the otherwise default: the Waterfall. The Waterfall is where decisions/orders only flow in 1 direction: the plan is set by higher-ups (i.e. Congress) and people across government must implement it, with no/little room to make further decisions. Pahlka's team is doing the hard work to tackle this, and it underscores something truly key to progress forward: **the ability of a team to learn as it goes**. Also fascinating was how this relates to procurement, and that a policy from the 60's considered software something the government should buy, just as it buys paperclips.

Here are a few early quotes from the book that I liked - 
- "**no one glitch**...core issues that are human rather than technological, complex rather than just complicated" (p. 15)
- "As long as the training manual is 800 pages, as long as 17-year veterans of the department are still getting up to speed, making the tech better will be of only marginal help. **Modernizing technology without rationalizing and simplifying the policy and process it must support seldom works**." (p. 53)
- **Cartoon waterfall**: with several pools, each flowing into the next. Separate, sequential stages. "Whereas it's a major sin in the waterfall model to change requirements at a later stage", agile welcomes it. (p. 58-59)
- **Connecting software developers with policy level leadership**: software developers care very much about the mission and "[t]hey knew where the bottlenecks were and what to do about them — they just needed someone from higher up the chain to listen to them, and [author Jennifer Pahlka's team] could make that happen."

Pahlka's a wonderful storyteller, and section and chapter titles stick with you. 
- Part I: The Waterfall (chapters including Seventeen Years, Concrete Boats)
- Part II: Mechanicals at the Gate (The Kodak Curse, The Procedure Fetish)
- Part III: User Needs, Not Government Needs (Byrne's Law, What We Believe Matters)

This is also the book where I learned that "it's easier to ask for forgiveness than to get permission" is attributed to Grace Hopper!

**Comment by monicagerber** [comment]
@stefaniebutland Thanks for tagging me here. :)

To build on @jules32's comment, the illustration of the Waterfall concept in government resonated with me because that is largely what exists in the healthcare and biomedical research environments where I've worked. In my experience, when you try to work in another way, you hit a lot of cultural and institutional resistance. I think for most people, myself included until recently, there's no understanding that there could be other ways of working and managing projects. If you work within a large institution with a Waterfall systems, can your smaller team/group/department still adopt agile methods?

Healthcare also faces the same challenges with archeological tech layers, with each layer an expression of archeological policy layers requiring even more specialized work (p. 39, 42). 

The part that really stuck with me was the description of the 'concrete boat' and disempowerment that government workers feel (p. 64). People tend to abdicate responsibility in order to avoid blame. How do people survive making concrete boats and following these kinds of norms for their entire careers? (see p. 141 also)

Phalka outlines some steps for building digital as a core competency in government (p. 267). This has helped me think about how I can support efforts to build data literacy in the healthcare space I work in. 

I mentioned a book club to some folks I work with in DaSL and a couple were interested. I'd love to invite them to join a conversation if that's ok with you @stefaniebutland!

**Comment by stefaniebutland** [comment]
Yes @monicagerber would be great to invite anyone interested! We put this in a public repo, rather than keeping our comments in Slack, for exactly that reason. Anyone is welcome to comment here and join a synch discussion.
I'm away Jan 8-10 so I'll come back to this late next week.

**Comment by stefaniebutland** [comment]
Scheduled for Tuesday, February 13, 12:00 - 1:00 pm PT / 3:00 - 4:00 ET via Zoom. 
Anyone is welcome. You don't even have to have read the book!
Let @stefaniebutland know if you'd like a calendar invite.

**Comment by mfisher87** [comment]
I'd love a calendar invite @stefaniebutland :)

**Comment by stefaniebutland** [comment]
Wow!! 12 people participated from NSIDC, NASA LP.DAAC, NOAA Fisheries, Fred Hutch, US DOI, Liminal, Openscapes! We had an incredible encouraging discussion among peers who don't typically get together. The community-feel of support for each other was so strong. 

Notes in [OpenscapesBookClub](https://docs.google.com/document/d/1feRy8mF95bNeesmSlnlhaE3P3wVelqnd2DyhiTV32UY/edit) doc
